### PR TITLE
remove fixed code url

### LINKED ISSUE #135: Fix hard-coded email links in bus email templates
Looks like we hard-coded brickhack.io as the domain in these emails...

* [ ] https://github.com/codeRIT/hackathon_manager/blob/master/app/views/mailer/bus_captain_confirmation_email.html.erb
* [ ] https://github.com/codeRIT/hackathon_manager/blob/master/app/views/mailer/bus_list_update_email.html.erb

Instead should use `_url` links like the ones here: https://github.com/codeRIT/hackathon_manager/blob/master/app/views/mailer/incomplete_reminder_email.html.erb

### PR DESCRIPTION
**Pull request by dquach217**
Fixed #135

### CODE REVIEW

**Comment by dquach217** [comment]
@sman591 do you know what's going on with Travis? My changes should not have caused any sort of errors

**Comment by sman591** [comment]
Rip, the bug is back. Idk what's going on here but code looks good to me, feel free to merge

**Comment by dquach217** [comment]
Closed #137

**Pull request merged**
